os: linux
language: go
go:
- 1.10

services:
  - docker

before_install:
  - export GOROOT=$(go env GOROOT)

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -u github.com/jstemmer/go-junit-report

script:
  - make
  - GENERATE_REPORT=1 make tests
  - GENERATE_REPORT=1 make lint
  - GENERATE_REPORT=1 make coverage
